name: deploy

on:
  workflow_run:
    workflows: ["pylint", "pytest"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: remote-ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 3.34.135.112
          username: ec2-user
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd cicd
            git pull
